### ISSUE TITLE
mysql无法获取注释的问题

### ISSUE THREAD

**Issue by kevery** [abel533/DBMetadata#2]
您好，我在基于springMVC，druid数据源构建的项目中使用了此jar包
但是无法获取表名备注和字段备注，经查询资料发现需指定两个参数
**useInformationSchema=true
remarks=true**
但druid数据源配置中无法配置这两个参数，所以我是在url中添加的，已解决问题
向您反馈，希望能作出优化或在README中说明
最后， 感谢您的无私奉献

**Comment by abel533** [comment]
mysql版本是多少？我在很多环境也试过，没有遇到过问题。

**Comment by kevery** [comment]
windows   5.5.37  
我不太确定是不是因为使用了连接池的原因

**Comment by abel533** [comment]
用简单数据源试试。

**Comment by tzy570978** [comment]
我的mysql是5.7.21，只是无法生成表的注释。我重写了SimpleDataSource的getConnection()的方法
 @Override
    public Connection getConnection() throws SQLException {
        if (delegate instanceof SimpleDataSource) {
            /**
             *
             * //如果是mysql那么需要设置里可以返回mysql的备注信息,应该只是一部分。
             */
            if (this.dialect.equals(Dialect.MYSQL)){
                Properties props =new Properties();
                props.setProperty("user", user);
                props.setProperty("password", pwd);
                props.setProperty("remarks", "true"); //设置可以获取remarks信息
                props.setProperty("useInformationSchema", "true");//设置可以获取tables remarks信息
                return DriverManager.getConnection(url,props);
            }
            return DriverManager.getConnection(url, user, pwd);
        } else {
            return delegate.getConnection();
        }
}
这样在可以有表的注释。但是有一个问题，就是速度会变慢。

**Comment by xkcoding** [comment]
可以获取到列的注释，但是仍然无法获取表的注释。@abel533

感谢 @tzy521521
